UPDATE public.alleys SET lane_count = 32 WHERE lower(name) = lower('Steel City Bowl and Brews') AND lower(city) = lower('Bethlehem') AND state = 'PA';
UPDATE public.alleys SET lane_count = 8 WHERE lower(name) = lower('Valley Lanes Bowling') AND lower(city) = lower('Sybertsville') AND state = 'PA';
UPDATE public.alleys SET lane_count = 32 WHERE lower(name) = lower('Harrisburg Escape Rooms at ABC East Lanes') AND lower(city) = lower('Harrisburg') AND state = 'PA';
UPDATE public.alleys SET lane_count = 8 WHERE lower(name) = lower('The Bowling Alley at The Meadows') AND lower(city) = lower('Washington') AND state = 'PA';
UPDATE public.alleys SET lane_count = 24 WHERE lower(name) = lower('Empire Bowl') AND lower(city) = lower('Sioux Falls') AND state = 'SD';
UPDATE public.alleys SET lane_count = 40 WHERE lower(name) = lower('Jack and Jill Lanes Lehi') AND lower(city) = lower('Lehi') AND state = 'UT';
UPDATE public.alleys SET lane_count = 24 WHERE lower(name) = lower('Bowl America Fairfax') AND lower(city) = lower('Fairfax') AND state = 'VA';
UPDATE public.alleys SET lane_count = 40 WHERE lower(name) = lower('Eastway Bowl') AND lower(city) = lower('Sioux Falls') AND state = 'SD';
UPDATE public.alleys SET lane_count = 8 WHERE lower(name) = lower('Pine Bowl') AND lower(city) = lower('Pine Bluffs') AND state = 'WY';
UPDATE public.alleys SET lane_count = 24 WHERE lower(name) = lower('Green River Bowling Center') AND lower(city) = lower('Green River') AND state = 'WY';
UPDATE public.alleys SET lane_count = 32 WHERE lower(name) = lower('Bowl America Falls Church') AND lower(city) = lower('Falls Church') AND state = 'VA';
UPDATE public.alleys SET lane_count = 16 WHERE lower(name) = lower('Frontier Lanes') AND lower(city) = lower('Ash Flat') AND state = 'AR';
UPDATE public.alleys SET lane_count = 40 WHERE lower(name) = lower('Riverside EpiCenter') AND lower(city) = lower('Austell') AND state = 'GA';
UPDATE public.alleys SET lane_count = 40 WHERE lower(name) = lower('Hijinx: The Funtivity Spot | Bowling, Laser Tag, Arcade Games, Ropes Course, Playground | JT''s Grill Restaurant') AND lower(city) = lower('Jonesboro') AND state = 'AR';
UPDATE public.alleys SET lane_count = 24 WHERE lower(name) = lower('Stars and Strikes') AND lower(city) = lower('Woodstock') AND state = 'GA';
UPDATE public.alleys SET lane_count = 24 WHERE lower(name) = lower('Stars and Strikes') AND lower(city) = lower('Dallas') AND state = 'GA';
UPDATE public.alleys SET lane_count = 24 WHERE lower(name) = lower('Royal Lanes Social') AND lower(city) = lower('Peachtree City') AND state = 'GA';
UPDATE public.alleys SET lane_count = 14 WHERE lower(name) = lower('Lucky Strike Philadelphia') AND lower(city) = lower('Philadelphia') AND state = 'PA';
UPDATE public.alleys SET lane_count = 24 WHERE lower(name) = lower('Tift County Lanes') AND lower(city) = lower('Tifton') AND state = 'GA';
UPDATE public.alleys SET lane_count = 8 WHERE lower(name) = lower('Kings Lanes') AND lower(city) = lower('Arlington') AND state = 'SD';
UPDATE public.alleys SET lane_count = 40 WHERE lower(name) = lower('The Painted Pin') AND lower(city) = lower('Atlanta') AND state = 'GA';
UPDATE public.alleys SET lane_count = 40 WHERE lower(name) = lower('Thunderzone') AND lower(city) = lower('Douglasville') AND state = 'GA';
UPDATE public.alleys SET lane_count = 40 WHERE lower(name) = lower('Roxbury Lanes') AND lower(city) = lower('Seattle') AND state = 'WA';
UPDATE public.alleys SET lane_count = 32 WHERE lower(name) = lower('Fairway Lanes') AND lower(city) = lower('Centralia') AND state = 'WA';
UPDATE public.alleys SET lane_count = 8 WHERE lower(name) = lower('CT Bowling Alley by RPM - Lanes') AND lower(city) = lower('Stamford') AND state = 'CT';
UPDATE public.alleys SET lane_count = 24 WHERE lower(name) = lower('Riverview Lanes Bowling Center') AND lower(city) = lower('Coulee Dam') AND state = 'WA';
UPDATE public.alleys SET lane_count = 24 WHERE lower(name) = lower('Prairie Lanes') AND lower(city) = lower('Yelm') AND state = 'WA';
UPDATE public.alleys SET lane_count = 16 WHERE lower(name) = lower('Champion Lanes') AND lower(city) = lower('Washington') AND state = 'IN';
UPDATE public.alleys SET lane_count = 32 WHERE lower(name) = lower('Secoma Lanes') AND lower(city) = lower('Federal Way') AND state = 'WA';
UPDATE public.alleys SET lane_count = 40 WHERE lower(name) = lower('Paradise Lanes Entertainment Center') AND lower(city) = lower('Tacoma') AND state = 'WA';
UPDATE public.alleys SET lane_count = 8 WHERE lower(name) = lower('Ten Spot Lanes Inc') AND lower(city) = lower('Mandan') AND state = 'ND';
UPDATE public.alleys SET lane_count = 14 WHERE lower(name) = lower('Lucky Strike Bellevue') AND lower(city) = lower('Bellevue') AND state = 'WA';
UPDATE public.alleys SET lane_count = 32 WHERE lower(name) = lower('Riverside Lanes') AND lower(city) = lower('Mount Vernon') AND state = 'WA';
UPDATE public.alleys SET lane_count = 24 WHERE lower(name) = lower('Shores Bowl') AND lower(city) = lower('Ocean Shores') AND state = 'WA';
UPDATE public.alleys SET lane_count = 32 WHERE lower(name) = lower('Strawberry Lanes') AND lower(city) = lower('Marysville') AND state = 'WA';
UPDATE public.alleys SET lane_count = 40 WHERE lower(name) = lower('Highland Park Bowl') AND lower(city) = lower('Los Angeles') AND state = 'CA';
UPDATE public.alleys SET lane_count = 40 WHERE lower(name) = lower('Comet Pub & Lanes') AND lower(city) = lower('Decatur') AND state = 'GA';
UPDATE public.alleys SET lane_count = 40 WHERE lower(name) = lower('Kenmore Lanes') AND lower(city) = lower('Kenmore') AND state = 'WA';
UPDATE public.alleys SET lane_count = 32 WHERE lower(name) = lower('The Wild Game Entertainment Experience - Evergreen') AND lower(city) = lower('Evergreen') AND state = 'CO';
UPDATE public.alleys SET lane_count = 32 WHERE lower(name) = lower('Revolutions By HeyDay') AND lower(city) = lower('Oklahoma City') AND state = 'OK';
UPDATE public.alleys SET lane_count = 32 WHERE lower(name) = lower('West Seattle Bowl') AND lower(city) = lower('Seattle') AND state = 'WA';
UPDATE public.alleys SET lane_count = 32 WHERE lower(name) = lower('Spare Time Lanes') AND lower(city) = lower('Kennewick') AND state = 'WA';
UPDATE public.alleys SET lane_count = 32 WHERE lower(name) = lower('Center Bowl') AND lower(city) = lower('Anchorage') AND state = 'AK';
UPDATE public.alleys SET lane_count = 24 WHERE lower(name) = lower('PinHeadz Bowling Center') AND lower(city) = lower('Colorado Springs') AND state = 'CO';
UPDATE public.alleys SET lane_count = 14 WHERE lower(name) = lower('Lucky Strike Denver') AND lower(city) = lower('Denver') AND state = 'CO';
UPDATE public.alleys SET lane_count = 24 WHERE lower(name) = lower('DECA+BOL') AND lower(city) = lower('Vail') AND state = 'CO';
UPDATE public.alleys SET lane_count = 40 WHERE lower(name) = lower('Pins Mechanical Co.') AND lower(city) = lower('Nashville') AND state = 'TN';
UPDATE public.alleys SET lane_count = 32 WHERE lower(name) = lower('King Pin Lanes') AND lower(city) = lower('Colorado Springs') AND state = 'CO';
UPDATE public.alleys SET lane_count = 8 WHERE lower(name) = lower('North Star Bowl') AND lower(city) = lower('Wilmington') AND state = 'VT';
UPDATE public.alleys SET lane_count = 24 WHERE lower(name) = lower('Brattleboro Bowl') AND lower(city) = lower('Brattleboro') AND state = 'VT';
UPDATE public.alleys SET lane_count = 36 WHERE lower(name) = lower('Bowlero Lakewood') AND lower(city) = lower('Lakewood') AND state = 'CO';
UPDATE public.alleys SET lane_count = 14 WHERE lower(name) = lower('Lucky Strike Atlantic Station') AND lower(city) = lower('Atlanta') AND state = 'GA';
UPDATE public.alleys SET lane_count = 8 WHERE lower(name) = lower('Wayne''s Lanes') AND lower(city) = lower('Canaan') AND state = 'VT';
UPDATE public.alleys SET lane_count = 16 WHERE lower(name) = lower('Village Lanes') AND lower(city) = lower('Green Bay') AND state = 'WI';
UPDATE public.alleys SET lane_count = 24 WHERE lower(name) = lower('Pioneer Bowl') AND lower(city) = lower('Richfield') AND state = 'WI';
UPDATE public.alleys SET lane_count = 24 WHERE lower(name) = lower('Play at The Broadmoor') AND lower(city) = lower('Colorado Springs') AND state = 'CO';
UPDATE public.alleys SET lane_count = 16 WHERE lower(name) = lower('Golden Lanes Inc') AND lower(city) = lower('Petersburg') AND state = 'WV';
UPDATE public.alleys SET lane_count = 24 WHERE lower(name) = lower('Bowling Center') AND lower(city) = lower('Enosburg Falls') AND state = 'VT';
UPDATE public.alleys SET lane_count = 16 WHERE lower(name) = lower('Holler House | Milwaukee and the Nation''s Oldest Alleys') AND lower(city) = lower('Milwaukee') AND state = 'WI';
UPDATE public.alleys SET lane_count = 24 WHERE lower(name) = lower('Woody''s Bowling Center') AND lower(city) = lower('Buckhannon') AND state = 'WV';
UPDATE public.alleys SET lane_count = 16 WHERE lower(name) = lower('South Branch Potomac Lanes') AND lower(city) = lower('Moorefield') AND state = 'WV';
UPDATE public.alleys SET lane_count = 14 WHERE lower(name) = lower('Lucky Strike Auburn') AND lower(city) = lower('Auburn') AND state = 'AL';
UPDATE public.alleys SET lane_count = 10 WHERE lower(name) = lower('Round1 Bowling & Arcade Southwest Plaza') AND lower(city) = lower('Littleton') AND state = 'CO';
UPDATE public.alleys SET lane_count = 8 WHERE lower(name) = lower('Gunter Lanes') AND lower(city) = lower('Montgomery') AND state = 'AL';
UPDATE public.alleys SET lane_count = 32 WHERE lower(name) = lower('AMF Pin Palace Lanes') AND lower(city) = lower('Huntsville') AND state = 'AL';
UPDATE public.alleys SET lane_count = 32 WHERE lower(name) = lower('Super Bowl Family Entertainment Center') AND lower(city) = lower('Appleton') AND state = 'WI';
UPDATE public.alleys SET lane_count = 8 WHERE lower(name) = lower('McCorvey''s Bowling World') AND lower(city) = lower('Pelham') AND state = 'AL';
UPDATE public.alleys SET lane_count = 40 WHERE lower(name) = lower('Vestavia Bowl') AND lower(city) = lower('Vestavia Hills') AND state = 'AL';
UPDATE public.alleys SET lane_count = 36 WHERE lower(name) = lower('Bowlero Montgomery') AND lower(city) = lower('Montgomery') AND state = 'AL';
UPDATE public.alleys SET lane_count = 40 WHERE lower(name) = lower('The Gulf Bowl Bowling Alley & Captain''s Choice Seafood Restaurant') AND lower(city) = lower('Foley') AND state = 'AL';
UPDATE public.alleys SET lane_count = 24 WHERE lower(name) = lower('Maxwell Bowling Center') AND lower(city) = lower('Montgomery') AND state = 'AL';
UPDATE public.alleys SET lane_count = 32 WHERE lower(name) = lower('Husted''s Hazel Dell Lanes') AND lower(city) = lower('Vancouver') AND state = 'WA';
UPDATE public.alleys SET lane_count = 8 WHERE lower(name) = lower('The Bowlin'' Alley') AND lower(city) = lower('Valley') AND state = 'AL';
UPDATE public.alleys SET lane_count = 36 WHERE lower(name) = lower('Bowlero Riverview') AND lower(city) = lower('Birmingham') AND state = 'AL';
UPDATE public.alleys SET lane_count = 32 WHERE lower(name) = lower('Bama Lanes') AND lower(city) = lower('Montgomery') AND state = 'AL';
UPDATE public.alleys SET lane_count = 40 WHERE lower(name) = lower('Allen''s Crosley Lanes') AND lower(city) = lower('Vancouver') AND state = 'WA';
UPDATE public.alleys SET lane_count = 32 WHERE lower(name) = lower('The Foundry Cinema & Bowl') AND lower(city) = lower('Fraser') AND state = 'CO';
UPDATE public.alleys SET lane_count = 16 WHERE lower(name) = lower('GoodTimes Bowling of Troy') AND lower(city) = lower('Troy') AND state = 'AL';
UPDATE public.alleys SET lane_count = 16 WHERE lower(name) = lower('State Street Lanes') AND lower(city) = lower('Hamburg') AND state = 'PA';
UPDATE public.alleys SET lane_count = 24 WHERE lower(name) = lower('Greenbrier Bowling and Recreation Center') AND lower(city) = lower('Lewisburg') AND state = 'WV';
UPDATE public.alleys SET lane_count = 24 WHERE lower(name) = lower('Pinheads - New River Gorge') AND lower(city) = lower('Oak Hill') AND state = 'WV';
UPDATE public.alleys SET lane_count = 40 WHERE lower(name) = lower('Bowlounge') AND lower(city) = lower('Dallas') AND state = 'TX';
UPDATE public.alleys SET lane_count = 32 WHERE lower(name) = lower('AMF River City Lanes') AND lower(city) = lower('Decatur') AND state = 'AL';
UPDATE public.alleys SET lane_count = 36 WHERE lower(name) = lower('Bowlero South Seattle') AND lower(city) = lower('Tukwila') AND state = 'WA';
UPDATE public.alleys SET lane_count = 24 WHERE lower(name) = lower('Suburban Lanes') AND lower(city) = lower('Morgantown') AND state = 'WV';
UPDATE public.alleys SET lane_count = 24 WHERE lower(name) = lower('Mountaineer Bowling Lanes') AND lower(city) = lower('Bluefield') AND state = 'WV';
UPDATE public.alleys SET lane_count = 24 WHERE lower(name) = lower('Fairmont Bowling Center') AND lower(city) = lower('Fairmont') AND state = 'WV';
UPDATE public.alleys SET lane_count = 32 WHERE lower(name) = lower('The 10th Frame') AND lower(city) = lower('Appleton') AND state = 'WI';
UPDATE public.alleys SET lane_count = 24 WHERE lower(name) = lower('Strike Zone Bowling Center') AND lower(city) = lower('Huntington') AND state = 'WV';
UPDATE public.alleys SET lane_count = 8 WHERE lower(name) = lower('Country Lanes Bowling Alley') AND lower(city) = lower('Spencer') AND state = 'WV';
UPDATE public.alleys SET lane_count = 24 WHERE lower(name) = lower('Leisure Lanes Inc') AND lower(city) = lower('Beckley') AND state = 'WV';
UPDATE public.alleys SET lane_count = 32 WHERE lower(name) = lower('Emerson Lanes') AND lower(city) = lower('Parkersburg') AND state = 'WV';
UPDATE public.alleys SET lane_count = 8 WHERE lower(name) = lower('Main Street Lanes') AND lower(city) = lower('Cross Plains') AND state = 'WI';
UPDATE public.alleys SET lane_count = 32 WHERE lower(name) = lower('Foxx View Lanes') AND lower(city) = lower('Waukesha') AND state = 'WI';
UPDATE public.alleys SET lane_count = 24 WHERE lower(name) = lower('Dogger''s Bar & Lanes') AND lower(city) = lower('Wautoma') AND state = 'WI';
UPDATE public.alleys SET lane_count = 8 WHERE lower(name) = lower('Township Bowl') AND lower(city) = lower('Hillsboro') AND state = 'WI';
UPDATE public.alleys SET lane_count = 24 WHERE lower(name) = lower('Galaxy Lanes') AND lower(city) = lower('Charleston') AND state = 'WV';
UPDATE public.alleys SET lane_count = 40 WHERE lower(name) = lower('Eastern Shore Lanes') AND lower(city) = lower('Spanish Fort') AND state = 'AL';
UPDATE public.alleys SET lane_count = 8 WHERE lower(name) = lower('Wisconsin State USBC') AND lower(city) = lower('Watertown') AND state = 'WI';
UPDATE public.alleys SET lane_count = 8 WHERE lower(name) = lower('Stars & Strikes of Princeton WI') AND lower(city) = lower('Princeton') AND state = 'WI';
UPDATE public.alleys SET lane_count = 32 WHERE lower(name) = lower('Spare Time Trussville') AND lower(city) = lower('Birmingham') AND state = 'AL';
UPDATE public.alleys SET lane_count = 16 WHERE lower(name) = lower('Lake Ripley Lanes') AND lower(city) = lower('Cambridge') AND state = 'WI';
UPDATE public.alleys SET lane_count = 16 WHERE lower(name) = lower('Juneau Lanes') AND lower(city) = lower('Juneau') AND state = 'WI';
UPDATE public.alleys SET lane_count = 40 WHERE lower(name) = lower('Oak Mountain Lanes') AND lower(city) = lower('Pelham') AND state = 'AL';
UPDATE public.alleys SET lane_count = 24 WHERE lower(name) = lower('Twin City Family Fun Center') AND lower(city) = lower('Barre') AND state = 'VT';
UPDATE public.alleys SET lane_count = 36 WHERE lower(name) = lower('Bowlero Wauwatosa') AND lower(city) = lower('Wauwatosa') AND state = 'WI';
UPDATE public.alleys SET lane_count = 32 WHERE lower(name) = lower('Pikeside Bowl') AND lower(city) = lower('Martinsburg') AND state = 'WV';
UPDATE public.alleys SET lane_count = 36 WHERE lower(name) = lower('Schwoegler Park Towne Lanes') AND lower(city) = lower('Madison') AND state = 'WI';
UPDATE public.alleys SET lane_count = 24 WHERE lower(name) = lower('Stowe Bowl') AND lower(city) = lower('Stowe') AND state = 'VT';
UPDATE public.alleys SET lane_count = 40 WHERE lower(name) = lower('AMF West Lanes') AND lower(city) = lower('Milwaukee') AND state = 'WI';
UPDATE public.alleys SET lane_count = 16 WHERE lower(name) = lower('Missisquoi Lanes') AND lower(city) = lower('Lowell') AND state = 'VT';
UPDATE public.alleys SET lane_count = 16 WHERE lower(name) = lower('Alley 304') AND lower(city) = lower('Clarksburg') AND state = 'WV';
UPDATE public.alleys SET lane_count = 36 WHERE lower(name) = lower('Bowlero Westminster') AND lower(city) = lower('Westminster') AND state = 'CO';
UPDATE public.alleys SET lane_count = 36 WHERE lower(name) = lower('Bowlero Heather Ridge') AND lower(city) = lower('Aurora') AND state = 'CO';
UPDATE public.alleys SET lane_count = 40 WHERE lower(name) = lower('Pinz Bowling Kitchen + Bar') AND lower(city) = lower('Studio City') AND state = 'CA';
UPDATE public.alleys SET lane_count = 14 WHERE lower(name) = lower('Lucky Strike Wheat Ridge') AND lower(city) = lower('Wheat Ridge') AND state = 'CO';
UPDATE public.alleys SET lane_count = 40 WHERE lower(name) = lower('AMF Colorado Springs Lanes') AND lower(city) = lower('Colorado Springs') AND state = 'CO';
UPDATE public.alleys SET lane_count = 14 WHERE lower(name) = lower('Lucky Strike Lone Tree') AND lower(city) = lower('Lone Tree') AND state = 'CO';
UPDATE public.alleys SET lane_count = 22 WHERE lower(name) = lower('Main Event Colorado Springs') AND lower(city) = lower('Colorado Springs') AND state = 'CO';
UPDATE public.alleys SET lane_count = 14 WHERE lower(name) = lower('Lucky Strike Clovis') AND lower(city) = lower('Clovis') AND state = 'CA';
UPDATE public.alleys SET lane_count = 32 WHERE lower(name) = lower('Triangle Bowl') AND lower(city) = lower('Longview') AND state = 'WA';
UPDATE public.alleys SET lane_count = 24 WHERE lower(name) = lower('River Alley') AND lower(city) = lower('St Albans') AND state = 'WV';
UPDATE public.alleys SET lane_count = 8 WHERE lower(name) = lower('Bowling Ball Beach') AND lower(city) = lower('Point Arena') AND state = 'CA';
UPDATE public.alleys SET lane_count = 14 WHERE lower(name) = lower('Lucky Strike Fresno') AND lower(city) = lower('Fresno') AND state = 'CA';
UPDATE public.alleys SET lane_count = 40 WHERE lower(name) = lower('XLanes') AND lower(city) = lower('Los Angeles') AND state = 'CA';
UPDATE public.alleys SET lane_count = 24 WHERE lower(name) = lower('Chelan Lanes') AND lower(city) = lower('Chelan') AND state = 'WA';
UPDATE public.alleys SET lane_count = 8 WHERE lower(name) = lower('Strikes Spares & Spirits') AND lower(city) = lower('Iron Ridge') AND state = 'WI';
UPDATE public.alleys SET lane_count = 32 WHERE lower(name) = lower('Spare Time Colchester') AND lower(city) = lower('Colchester') AND state = 'VT';
UPDATE public.alleys SET lane_count = 24 WHERE lower(name) = lower('Gold Crown Lanes') AND lower(city) = lower('St Johnsbury') AND state = 'VT';
UPDATE public.alleys SET lane_count = 24 WHERE lower(name) = lower('Bluemound Bowl') AND lower(city) = lower('Brookfield') AND state = 'WI';
UPDATE public.alleys SET lane_count = 32 WHERE lower(name) = lower('Lake Bowl') AND lower(city) = lower('Moses Lake') AND state = 'WA';
UPDATE public.alleys SET lane_count = 14 WHERE lower(name) = lower('Lucky Strike Lanes Inc') AND lower(city) = lower('Mansfield Center') AND state = 'CT';
UPDATE public.alleys SET lane_count = 32 WHERE lower(name) = lower('Big Bear Bowling Barn') AND lower(city) = lower('Big Bear Lake') AND state = 'CA';
UPDATE public.alleys SET lane_count = 24 WHERE lower(name) = lower('Rutland Bowlerama Inc.') AND lower(city) = lower('Rutland') AND state = 'VT';
UPDATE public.alleys SET lane_count = 40 WHERE lower(name) = lower('ABC East Lanes') AND lower(city) = lower('Harrisburg') AND state = 'PA';
UPDATE public.alleys SET lane_count = 32 WHERE lower(name) = lower('Norwich Bowling & Entertainment Center') AND lower(city) = lower('Norwich') AND state = 'CT';
UPDATE public.alleys SET lane_count = 32 WHERE lower(name) = lower('Bowl-A-Vard') AND lower(city) = lower('Madison') AND state = 'WI';
UPDATE public.alleys SET lane_count = 24 WHERE lower(name) = lower('Danbury Duckpin Lanes') AND lower(city) = lower('Danbury') AND state = 'CT';
UPDATE public.alleys SET lane_count = 32 WHERE lower(name) = lower('Bellevue Bowl') AND lower(city) = lower('Atwater') AND state = 'CA';
UPDATE public.alleys SET lane_count = 24 WHERE lower(name) = lower('Highland Bowl') AND lower(city) = lower('Cheshire') AND state = 'CT';
UPDATE public.alleys SET lane_count = 8 WHERE lower(name) = lower('Woodlawn Duckpin Bowling') AND lower(city) = lower('West Haven') AND state = 'CT';
UPDATE public.alleys SET lane_count = 36 WHERE lower(name) = lower('Bowlero Cherry Creek') AND lower(city) = lower('Denver') AND state = 'CO';
UPDATE public.alleys SET lane_count = 32 WHERE lower(name) = lower('Spare Time Bristol') AND lower(city) = lower('Bristol') AND state = 'CT';
UPDATE public.alleys SET lane_count = 36 WHERE lower(name) = lower('Bowlero Wallingford') AND lower(city) = lower('Wallingford') AND state = 'CT';
UPDATE public.alleys SET lane_count = 32 WHERE lower(name) = lower('Callahan''s Bowl-O-Rama') AND lower(city) = lower('Newington') AND state = 'CT';
UPDATE public.alleys SET lane_count = 32 WHERE lower(name) = lower('Revolutions Bowling and Lounge') AND lower(city) = lower('South Windsor') AND state = 'CT';
UPDATE public.alleys SET lane_count = 14 WHERE lower(name) = lower('Lucky Strike Visalia') AND lower(city) = lower('Visalia') AND state = 'CA';
UPDATE public.alleys SET lane_count = 16 WHERE lower(name) = lower('Ducks on the Ave') AND lower(city) = lower('Hartford') AND state = 'CT';
UPDATE public.alleys SET lane_count = 32 WHERE lower(name) = lower('Nutmeg Bowl') AND lower(city) = lower('Fairfield') AND state = 'CT';
UPDATE public.alleys SET lane_count = 40 WHERE lower(name) = lower('Hall of Fame Silver Lanes') AND lower(city) = lower('East Hartford') AND state = 'CT';
UPDATE public.alleys SET lane_count = 36 WHERE lower(name) = lower('Bowlero Norwalk') AND lower(city) = lower('Norwalk') AND state = 'CT';
UPDATE public.alleys SET lane_count = 14 WHERE lower(name) = lower('Lucky Strike Milford') AND lower(city) = lower('Milford') AND state = 'CT';
UPDATE public.alleys SET lane_count = 14 WHERE lower(name) = lower('Lucky Strike Kennesaw') AND lower(city) = lower('Kennesaw') AND state = 'GA';
UPDATE public.alleys SET lane_count = 40 WHERE lower(name) = lower('Pin Strikes - Stockbridge') AND lower(city) = lower('Stockbridge') AND state = 'GA';
UPDATE public.alleys SET lane_count = 40 WHERE lower(name) = lower('Pin Strikes Macon') AND lower(city) = lower('Macon') AND state = 'GA';
UPDATE public.alleys SET lane_count = 40 WHERE lower(name) = lower('The Painted Duck') AND lower(city) = lower('Atlanta') AND state = 'GA';
UPDATE public.alleys SET lane_count = 40 WHERE lower(name) = lower('Bowl 360 Strike City Spring Hill') AND lower(city) = lower('Spring Hill') AND state = 'FL';
UPDATE public.alleys SET lane_count = 32 WHERE lower(name) = lower('Spare Time Vernon') AND lower(city) = lower('Vernon') AND state = 'CT';
UPDATE public.alleys SET lane_count = 40 WHERE lower(name) = lower('Rigby''s Entertainment Complex') AND lower(city) = lower('Warner Robins') AND state = 'GA';
UPDATE public.alleys SET lane_count = 24 WHERE lower(name) = lower('Stars and Strikes') AND lower(city) = lower('Stone Mountain') AND state = 'GA';
UPDATE public.alleys SET lane_count = 40 WHERE lower(name) = lower('Strike 10 Bowling') AND lower(city) = lower('Hallandale Beach') AND state = 'FL';
UPDATE public.alleys SET lane_count = 22 WHERE lower(name) = lower('Main Event Suwanee') AND lower(city) = lower('Suwanee') AND state = 'GA';
UPDATE public.alleys SET lane_count = 22 WHERE lower(name) = lower('Main Event Alpharetta') AND lower(city) = lower('Alpharetta') AND state = 'GA';
UPDATE public.alleys SET lane_count = 40 WHERE lower(name) = lower('Incredibowl Entertainment Winter Haven') AND lower(city) = lower('Winter Haven') AND state = 'FL';
UPDATE public.alleys SET lane_count = 8 WHERE lower(name) = lower('Fusion Bowling') AND lower(city) = lower('Ponte Vedra Beach') AND state = 'FL';
UPDATE public.alleys SET lane_count = 22 WHERE lower(name) = lower('Main Event Orlando') AND lower(city) = lower('Orlando') AND state = 'FL';
UPDATE public.alleys SET lane_count = 14 WHERE lower(name) = lower('Lucky Strike Chamblee') AND lower(city) = lower('Atlanta') AND state = 'GA';
UPDATE public.alleys SET lane_count = 22 WHERE lower(name) = lower('Main Event Atlanta') AND lower(city) = lower('Atlanta') AND state = 'GA';
UPDATE public.alleys SET lane_count = 36 WHERE lower(name) = lower('Bowlero Lakeland') AND lower(city) = lower('Lakeland') AND state = 'FL';
UPDATE public.alleys SET lane_count = 24 WHERE lower(name) = lower('Green Valley Bowling Center') AND lower(city) = lower('Bluefield') AND state = 'WV';
UPDATE public.alleys SET lane_count = 8 WHERE lower(name) = lower('Bowlmor') AND lower(city) = lower('Sycamore') AND state = 'OH';
UPDATE public.alleys SET lane_count = 32 WHERE lower(name) = lower('Miracle Bowl') AND lower(city) = lower('Orem') AND state = 'UT';
UPDATE public.alleys SET lane_count = 40 WHERE lower(name) = lower('Nashville Underground') AND lower(city) = lower('Nashville') AND state = 'TN';
UPDATE public.alleys SET lane_count = 40 WHERE lower(name) = lower('Royal Z Lanes-Spring Valley') AND lower(city) = lower('Columbia') AND state = 'SC';
UPDATE public.alleys SET lane_count = 40 WHERE lower(name) = lower('Strikers Family SportsCenter') AND lower(city) = lower('Rock Hill') AND state = 'SC';
UPDATE public.alleys SET lane_count = 24 WHERE lower(name) = lower('Stars and Strikes') AND lower(city) = lower('Summerville') AND state = 'SC';
UPDATE public.alleys SET lane_count = 36 WHERE lower(name) = lower('Bowlero Sawmill') AND lower(city) = lower('Columbus') AND state = 'OH';
UPDATE public.alleys SET lane_count = 16 WHERE lower(name) = lower('Wickford Lanes') AND lower(city) = lower('North Kingstown') AND state = 'RI';
UPDATE public.alleys SET lane_count = 24 WHERE lower(name) = lower('Ryan Family Amusements (Formerly Walnut Hill Lanes) - Walnut Hill') AND lower(city) = lower('Woonsocket') AND state = 'RI';
UPDATE public.alleys SET lane_count = 32 WHERE lower(name) = lower('Surfside Bowling Entertainment Center') AND lower(city) = lower('Surfside Beach') AND state = 'SC';
UPDATE public.alleys SET lane_count = 24 WHERE lower(name) = lower('Alley Katz Bowling Center') AND lower(city) = lower('Westerly') AND state = 'RI';
UPDATE public.alleys SET lane_count = 24 WHERE lower(name) = lower('Goshen Lanes') AND lower(city) = lower('Mechanicsburg') AND state = 'OH';
UPDATE public.alleys SET lane_count = 24 WHERE lower(name) = lower('Breaktime Bowl and Bar Events') AND lower(city) = lower('Pawtucket') AND state = 'RI';
UPDATE public.alleys SET lane_count = 24 WHERE lower(name) = lower('Legion Bowl and Billiards') AND lower(city) = lower('Cranston') AND state = 'RI';
UPDATE public.alleys SET lane_count = 24 WHERE lower(name) = lower('Dudek Bowling Lanes') AND lower(city) = lower('Warren') AND state = 'RI';
UPDATE public.alleys SET lane_count = 40 WHERE lower(name) = lower('Paradise Lanes & FEC') AND lower(city) = lower('Spartanburg') AND state = 'SC';
UPDATE public.alleys SET lane_count = 32 WHERE lower(name) = lower('East Providence Lanes') AND lower(city) = lower('Rumford') AND state = 'RI';
UPDATE public.alleys SET lane_count = 32 WHERE lower(name) = lower('Old Mountain Lanes') AND lower(city) = lower('Wakefield') AND state = 'RI';
UPDATE public.alleys SET lane_count = 36 WHERE lower(name) = lower('Bowlero Cranston') AND lower(city) = lower('Cranston') AND state = 'RI';
UPDATE public.alleys SET lane_count = 32 WHERE lower(name) = lower('Spare Time Greenville') AND lower(city) = lower('Greenville') AND state = 'SC';
UPDATE public.alleys SET lane_count = 24 WHERE lower(name) = lower('Meadowbrook Lanes') AND lower(city) = lower('Warwick') AND state = 'RI';
UPDATE public.alleys SET lane_count = 32 WHERE lower(name) = lower('Southgate Bowling Center') AND lower(city) = lower('Florence') AND state = 'SC';
UPDATE public.alleys SET lane_count = 32 WHERE lower(name) = lower('Boulevard Lanes') AND lower(city) = lower('Anderson') AND state = 'SC';
UPDATE public.alleys SET lane_count = 36 WHERE lower(name) = lower('Bowlero Greenville') AND lower(city) = lower('Greenville') AND state = 'SC';
UPDATE public.alleys SET lane_count = 8 WHERE lower(name) = lower('Ivy Lanes') AND lower(city) = lower('Columbia') AND state = 'SC';
UPDATE public.alleys SET lane_count = 40 WHERE lower(name) = lower('Myrtle Beach Bowl') AND lower(city) = lower('Myrtle Beach') AND state = 'SC';
UPDATE public.alleys SET lane_count = 24 WHERE lower(name) = lower('Century Lanes Bowling Alley') AND lower(city) = lower('Columbia') AND state = 'SC';
UPDATE public.alleys SET lane_count = 40 WHERE lower(name) = lower('Star Lanes Polaris') AND lower(city) = lower('Columbus') AND state = 'OH';
UPDATE public.alleys SET lane_count = 32 WHERE lower(name) = lower('Anchor Lanes') AND lower(city) = lower('Irmo') AND state = 'SC';
UPDATE public.alleys SET lane_count = 14 WHERE lower(name) = lower('Lucky Strike Cayce') AND lower(city) = lower('Cayce') AND state = 'SC';
UPDATE public.alleys SET lane_count = 32 WHERE lower(name) = lower('Beltline Lanes') AND lower(city) = lower('Columbia') AND state = 'SC';
UPDATE public.alleys SET lane_count = 32 WHERE lower(name) = lower('Tullahoma Bowling Lanes') AND lower(city) = lower('Tullahoma') AND state = 'TN';
UPDATE public.alleys SET lane_count = 24 WHERE lower(name) = lower('Kingstown Bowl') AND lower(city) = lower('North Kingstown') AND state = 'RI';
UPDATE public.alleys SET lane_count = 40 WHERE lower(name) = lower('Hendersonville Strike & Spare Family Fun Center') AND lower(city) = lower('Hendersonville') AND state = 'TN';
UPDATE public.alleys SET lane_count = 40 WHERE lower(name) = lower('KingPins Family Entertainment Center') AND lower(city) = lower('Portland') AND state = 'OR';
UPDATE public.alleys SET lane_count = 32 WHERE lower(name) = lower('Donelson Plaza Strike and Spare') AND lower(city) = lower('Nashville') AND state = 'TN';
UPDATE public.alleys SET lane_count = 32 WHERE lower(name) = lower('AMF Seven Oaks Lanes') AND lower(city) = lower('Columbia') AND state = 'SC';
UPDATE public.alleys SET lane_count = 40 WHERE lower(name) = lower('Tenn Pin Alley') AND lower(city) = lower('Columbia') AND state = 'TN';
UPDATE public.alleys SET lane_count = 40 WHERE lower(name) = lower('Brooklyn Bowl Nashville') AND lower(city) = lower('Nashville') AND state = 'TN';
UPDATE public.alleys SET lane_count = 24 WHERE lower(name) = lower('Tusculum Strike & Spare') AND lower(city) = lower('Nashville') AND state = 'TN';
UPDATE public.alleys SET lane_count = 40 WHERE lower(name) = lower('Eastside Bowl') AND lower(city) = lower('Madison') AND state = 'TN';
UPDATE public.alleys SET lane_count = 40 WHERE lower(name) = lower('Lang''s Bowlarama') AND lower(city) = lower('Cranston') AND state = 'RI';
UPDATE public.alleys SET lane_count = 24 WHERE lower(name) = lower('Stars and Strikes') AND lower(city) = lower('Smyrna') AND state = 'TN';
UPDATE public.alleys SET lane_count = 24 WHERE lower(name) = lower('BYU Bowling & Games Center') AND lower(city) = lower('Provo') AND state = 'UT';
UPDATE public.alleys SET lane_count = 40 WHERE lower(name) = lower('Silva Lanes') AND lower(city) = lower('Albuquerque') AND state = 'NM';
UPDATE public.alleys SET lane_count = 40 WHERE lower(name) = lower('Smyrna Bowling Center') AND lower(city) = lower('Smyrna') AND state = 'TN';
UPDATE public.alleys SET lane_count = 40 WHERE lower(name) = lower('Delton Lanes') AND lower(city) = lower('Riverton') AND state = 'UT';
UPDATE public.alleys SET lane_count = 16 WHERE lower(name) = lower('Union Recreation') AND lower(city) = lower('Salt Lake City') AND state = 'UT';
UPDATE public.alleys SET lane_count = 32 WHERE lower(name) = lower('Ashley Lanes Tavern') AND lower(city) = lower('Charleston') AND state = 'SC';
UPDATE public.alleys SET lane_count = 40 WHERE lower(name) = lower('All Star Bowling & Entertainment - Draper') AND lower(city) = lower('Draper') AND state = 'UT';
UPDATE public.alleys SET lane_count = 40 WHERE lower(name) = lower('Thunder Alley Family Entertainment Center') AND lower(city) = lower('Dickson') AND state = 'TN';
UPDATE public.alleys SET lane_count = 8 WHERE lower(name) = lower('Pin Heads') AND lower(city) = lower('Helper') AND state = 'UT';
UPDATE public.alleys SET lane_count = 32 WHERE lower(name) = lower('All Star Bowling & Entertainment - Sandy') AND lower(city) = lower('Sandy') AND state = 'UT';
UPDATE public.alleys SET lane_count = 32 WHERE lower(name) = lower('Valley Bowling Lanes') AND lower(city) = lower('West Valley City') AND state = 'UT';
UPDATE public.alleys SET lane_count = 40 WHERE lower(name) = lower('Delton Lanes') AND lower(city) = lower('West Valley City') AND state = 'UT';
UPDATE public.alleys SET lane_count = 24 WHERE lower(name) = lower('Lakes Lanes Bowling Alley') AND lower(city) = lower('The Colony') AND state = 'TX';
UPDATE public.alleys SET lane_count = 32 WHERE lower(name) = lower('Strike City Lanes') AND lower(city) = lower('Eugene') AND state = 'OR';
UPDATE public.alleys SET lane_count = 40 WHERE lower(name) = lower('All Star Bowling & Entertainment - West Jordan') AND lower(city) = lower('West Jordan') AND state = 'UT';
UPDATE public.alleys SET lane_count = 24 WHERE lower(name) = lower('Seaview Lanes Bowling Center - ON US MILITARY BASE') AND lower(city) = lower('Newport') AND state = 'RI';
UPDATE public.alleys SET lane_count = 36 WHERE lower(name) = lower('Bowlero Dallas') AND lower(city) = lower('Addison') AND state = 'TX';
UPDATE public.alleys SET lane_count = 32 WHERE lower(name) = lower('Olympus Hills Bowling Lanes') AND lower(city) = lower('Millcreek') AND state = 'UT';
UPDATE public.alleys SET lane_count = 32 WHERE lower(name) = lower('Bountiful Bowl') AND lower(city) = lower('Bountiful') AND state = 'UT';
UPDATE public.alleys SET lane_count = 14 WHERE lower(name) = lower('Lucky Strike Garland') AND lower(city) = lower('Garland') AND state = 'TX';
UPDATE public.alleys SET lane_count = 14 WHERE lower(name) = lower('Lucky Strike San Antonio') AND lower(city) = lower('San Antonio') AND state = 'TX';
UPDATE public.alleys SET lane_count = 32 WHERE lower(name) = lower('810 Billiards & Bowling - Greenville') AND lower(city) = lower('Greenville') AND state = 'SC';
UPDATE public.alleys SET lane_count = 32 WHERE lower(name) = lower('Crossroads Bowling Center') AND lower(city) = lower('Beaumont') AND state = 'TX';
UPDATE public.alleys SET lane_count = 40 WHERE lower(name) = lower('PrimeTime Family Entertainment Center') AND lower(city) = lower('Abilene') AND state = 'TX';
UPDATE public.alleys SET lane_count = 24 WHERE lower(name) = lower('Palestine Bowling Center') AND lower(city) = lower('Palestine') AND state = 'TX';
UPDATE public.alleys SET lane_count = 14 WHERE lower(name) = lower('Lucky Strike Webster') AND lower(city) = lower('Webster') AND state = 'TX';
UPDATE public.alleys SET lane_count = 32 WHERE lower(name) = lower('Castro Village Bowl') AND lower(city) = lower('Castro Valley') AND state = 'CA';
UPDATE public.alleys SET lane_count = 40 WHERE lower(name) = lower('Astro SuperBowl') AND lower(city) = lower('Houston') AND state = 'TX';
UPDATE public.alleys SET lane_count = 40 WHERE lower(name) = lower('Pinstack Plano') AND lower(city) = lower('Plano') AND state = 'TX';
UPDATE public.alleys SET lane_count = 14 WHERE lower(name) = lower('Lucky Strikes') AND lower(city) = lower('Erie') AND state = 'KS';