UPDATE public.alleys SET lane_count = 16 WHERE lower(name) = lower('Cedar Park Bowling Lanes') AND lower(city) = lower('Anaconda') AND state = 'MT';
UPDATE public.alleys SET lane_count = 8 WHERE lower(name) = lower('Cedar Lanes') AND lower(city) = lower('Sidney') AND state = 'NE';
UPDATE public.alleys SET lane_count = 8 WHERE lower(name) = lower('Utica Lanes') AND lower(city) = lower('Utica') AND state = 'NE';
UPDATE public.alleys SET lane_count = 8 WHERE lower(name) = lower('Longhorn Lanes') AND lower(city) = lower('Burwell') AND state = 'NE';
UPDATE public.alleys SET lane_count = 8 WHERE lower(name) = lower('The Alley') AND lower(city) = lower('Humphrey') AND state = 'NE';
UPDATE public.alleys SET lane_count = 32 WHERE lower(name) = lower('Mockingbird Lanes') AND lower(city) = lower('Omaha') AND state = 'NE';
UPDATE public.alleys SET lane_count = 8 WHERE lower(name) = lower('Cambridge Lanes') AND lower(city) = lower('Cambridge') AND state = 'NE';
UPDATE public.alleys SET lane_count = 24 WHERE lower(name) = lower('Westbrook Lanes Inc') AND lower(city) = lower('Columbus') AND state = 'NE';
UPDATE public.alleys SET lane_count = 8 WHERE lower(name) = lower('Alley Cats Bowling') AND lower(city) = lower('Red Cloud') AND state = 'NE';
UPDATE public.alleys SET lane_count = 8 WHERE lower(name) = lower('Newman Grove Bowling') AND lower(city) = lower('Newman Grove') AND state = 'NE';
UPDATE public.alleys SET lane_count = 16 WHERE lower(name) = lower('Big Sky Lanes & Casino') AND lower(city) = lower('Eureka') AND state = 'MT';
UPDATE public.alleys SET lane_count = 16 WHERE lower(name) = lower('Arbor Lanes') AND lower(city) = lower('Nebraska City') AND state = 'NE';
UPDATE public.alleys SET lane_count = 32 WHERE lower(name) = lower('West Lanes Bowling Center') AND lower(city) = lower('Omaha') AND state = 'NE';
UPDATE public.alleys SET lane_count = 8 WHERE lower(name) = lower('Kingpin Lanes') AND lower(city) = lower('Gordon') AND state = 'NE';
UPDATE public.alleys SET lane_count = 24 WHERE lower(name) = lower('Chop''s Bowling Alley') AND lower(city) = lower('Omaha') AND state = 'NE';
UPDATE public.alleys SET lane_count = 16 WHERE lower(name) = lower('The Alley') AND lower(city) = lower('Bellevue') AND state = 'NE';
UPDATE public.alleys SET lane_count = 16 WHERE lower(name) = lower('Châm Pang Lanes') AND lower(city) = lower('Omaha') AND state = 'NE';
UPDATE public.alleys SET lane_count = 32 WHERE lower(name) = lower('Spare Time Omaha') AND lower(city) = lower('Omaha') AND state = 'NE';
UPDATE public.alleys SET lane_count = 16 WHERE lower(name) = lower('Victory Lanes') AND lower(city) = lower('Deer Lodge') AND state = 'MT';
UPDATE public.alleys SET lane_count = 40 WHERE lower(name) = lower('Maplewood Lanes') AND lower(city) = lower('Omaha') AND state = 'NE';
UPDATE public.alleys SET lane_count = 24 WHERE lower(name) = lower('Fireside Lanes') AND lower(city) = lower('Billings') AND state = 'MT';
UPDATE public.alleys SET lane_count = 24 WHERE lower(name) = lower('Ravalli Fun Center') AND lower(city) = lower('Hamilton') AND state = 'MT';
UPDATE public.alleys SET lane_count = 8 WHERE lower(name) = lower('Ennis Fish Bowl') AND lower(city) = lower('Ennis') AND state = 'MT';
UPDATE public.alleys SET lane_count = 16 WHERE lower(name) = lower('Sunset Bowl') AND lower(city) = lower('Billings') AND state = 'MT';
UPDATE public.alleys SET lane_count = 16 WHERE lower(name) = lower('Snowy Lanes') AND lower(city) = lower('Lewistown') AND state = 'MT';
UPDATE public.alleys SET lane_count = 8 WHERE lower(name) = lower('Glacier Lanes LLC') AND lower(city) = lower('Cut Bank') AND state = 'MT';
UPDATE public.alleys SET lane_count = 8 WHERE lower(name) = lower('Evergreen Lanes') AND lower(city) = lower('Forsyth') AND state = 'MT';
UPDATE public.alleys SET lane_count = 32 WHERE lower(name) = lower('Little''s Lanes') AND lower(city) = lower('Great Falls') AND state = 'MT';
UPDATE public.alleys SET lane_count = 8 WHERE lower(name) = lower('Lucky Strike Lanes') AND lower(city) = lower('Ronan') AND state = 'MT';
UPDATE public.alleys SET lane_count = 16 WHERE lower(name) = lower('Dave''s 32 oz Bar Grill & Bowling') AND lower(city) = lower('Boulder') AND state = 'MT';
UPDATE public.alleys SET lane_count = 16 WHERE lower(name) = lower('Trojan Lanes') AND lower(city) = lower('Troy') AND state = 'MT';
UPDATE public.alleys SET lane_count = 24 WHERE lower(name) = lower('Coyote Lanes and Roadrunner Cafe') AND lower(city) = lower('Shelby') AND state = 'MT';
UPDATE public.alleys SET lane_count = 8 WHERE lower(name) = lower('Treasure Lanes') AND lower(city) = lower('Livingston') AND state = 'MT';
UPDATE public.alleys SET lane_count = 24 WHERE lower(name) = lower('The Bozeman Bowl') AND lower(city) = lower('Bozeman') AND state = 'MT';
UPDATE public.alleys SET lane_count = 10 WHERE lower(name) = lower('Round1 Bowling & Arcade Gateway Mall') AND lower(city) = lower('Lincoln') AND state = 'NE';
UPDATE public.alleys SET lane_count = 24 WHERE lower(name) = lower('Yankee Lanes') AND lower(city) = lower('Keene') AND state = 'NH';
UPDATE public.alleys SET lane_count = 16 WHERE lower(name) = lower('Leda''s LightHouse') AND lower(city) = lower('Nashua') AND state = 'NH';
UPDATE public.alleys SET lane_count = 32 WHERE lower(name) = lower('Need 2 Speed') AND lower(city) = lower('Reno') AND state = 'NV';
UPDATE public.alleys SET lane_count = 10 WHERE lower(name) = lower('Round1 Bowling & Arcade Meadows Mall') AND lower(city) = lower('Las Vegas') AND state = 'NV';
UPDATE public.alleys SET lane_count = 10 WHERE lower(name) = lower('Round1 Bowling & Arcade Meadowood Mall') AND lower(city) = lower('Reno') AND state = 'NV';
UPDATE public.alleys SET lane_count = 8 WHERE lower(name) = lower('10 Pin Alley') AND lower(city) = lower('Nevada') AND state = 'MO';
UPDATE public.alleys SET lane_count = 16 WHERE lower(name) = lower('Sports Bowl & Wobbly Pin Food Truck') AND lower(city) = lower('Nevada') AND state = 'IA';
UPDATE public.alleys SET lane_count = 8 WHERE lower(name) = lower('Strike Bowl') AND lower(city) = lower('Laughlin') AND state = 'NV';
UPDATE public.alleys SET lane_count = 8 WHERE lower(name) = lower('Bob & Willie''s Wonderbowl - Blue Sky') AND lower(city) = lower('Omaha') AND state = 'NE';
UPDATE public.alleys SET lane_count = 24 WHERE lower(name) = lower('Riverside Lanes Bowling') AND lower(city) = lower('Laughlin') AND state = 'NV';
UPDATE public.alleys SET lane_count = 8 WHERE lower(name) = lower('Virgin River Bowling Alley') AND lower(city) = lower('Mesquite') AND state = 'NV';
UPDATE public.alleys SET lane_count = 32 WHERE lower(name) = lower('Spare Time Bowling Center') AND lower(city) = lower('Winnemucca') AND state = 'NV';
UPDATE public.alleys SET lane_count = 32 WHERE lower(name) = lower('High Sierra Lanes') AND lower(city) = lower('Reno') AND state = 'NV';
UPDATE public.alleys SET lane_count = 24 WHERE lower(name) = lower('Frontier Fun Center') AND lower(city) = lower('Fernley') AND state = 'NV';
UPDATE public.alleys SET lane_count = 50 WHERE lower(name) = lower('Grand Bowling Center') AND lower(city) = lower('Reno') AND state = 'NV';
UPDATE public.alleys SET lane_count = 24 WHERE lower(name) = lower('Boulder Bowl') AND lower(city) = lower('Boulder City') AND state = 'NV';
UPDATE public.alleys SET lane_count = 8 WHERE lower(name) = lower('Sage Brush Bowling Alley') AND lower(city) = lower('Fallon') AND state = 'NV';
UPDATE public.alleys SET lane_count = 32 WHERE lower(name) = lower('PiNZ Bowl') AND lower(city) = lower('Portsmouth') AND state = 'NH';
UPDATE public.alleys SET lane_count = 24 WHERE lower(name) = lower('Strikers East Bowling Center') AND lower(city) = lower('Raymond') AND state = 'NH';
UPDATE public.alleys SET lane_count = 32 WHERE lower(name) = lower('Bowl-O-Rama Family Fun Center') AND lower(city) = lower('Portsmouth') AND state = 'NH';
UPDATE public.alleys SET lane_count = 24 WHERE lower(name) = lower('Meyer Maple Lanes Bowling Alley') AND lower(city) = lower('Claremont') AND state = 'NH';
UPDATE public.alleys SET lane_count = 24 WHERE lower(name) = lower('North Country Bowling Center') AND lower(city) = lower('Berlin') AND state = 'NH';
UPDATE public.alleys SET lane_count = 24 WHERE lower(name) = lower('Lakeside Lanes') AND lower(city) = lower('Manchester') AND state = 'NH';
UPDATE public.alleys SET lane_count = 16 WHERE lower(name) = lower('King Bowling Lanes') AND lower(city) = lower('Goffstown') AND state = 'NH';
UPDATE public.alleys SET lane_count = 32 WHERE lower(name) = lower('Merrimack Ten Pin') AND lower(city) = lower('Merrimack') AND state = 'NH';
UPDATE public.alleys SET lane_count = 24 WHERE lower(name) = lower('Boutwell''s Bowling Center') AND lower(city) = lower('Concord') AND state = 'NH';
UPDATE public.alleys SET lane_count = 16 WHERE lower(name) = lower('Bowling') AND lower(city) = lower('Pahrump') AND state = 'NV';
UPDATE public.alleys SET lane_count = 24 WHERE lower(name) = lower('Exeter Bowling Lanes') AND lower(city) = lower('Exeter') AND state = 'NH';
UPDATE public.alleys SET lane_count = 40 WHERE lower(name) = lower('Yankee Lanes') AND lower(city) = lower('Manchester') AND state = 'NH';
UPDATE public.alleys SET lane_count = 8 WHERE lower(name) = lower('Rattlesnake Lanes') AND lower(city) = lower('Yerington') AND state = 'NV';
UPDATE public.alleys SET lane_count = 50 WHERE lower(name) = lower('Bowler City') AND lower(city) = lower('Hackensack') AND state = 'NJ';
UPDATE public.alleys SET lane_count = 14 WHERE lower(name) = lower('Lucky Strike Cherry Hill') AND lower(city) = lower('Cherry Hill Township') AND state = 'NJ';
UPDATE public.alleys SET lane_count = 14 WHERE lower(name) = lower('Lucky Strike Elkhorn') AND lower(city) = lower('Elkhorn') AND state = 'NE';
UPDATE public.alleys SET lane_count = 8 WHERE lower(name) = lower('RevRates VIP - Bowling Entertainment') AND lower(city) = lower('Howell Township') AND state = 'NJ';
UPDATE public.alleys SET lane_count = 28 WHERE lower(name) = lower('Bowl 360 Astoria') AND lower(city) = lower('Astoria') AND state = 'NY';
UPDATE public.alleys SET lane_count = 40 WHERE lower(name) = lower('Melody Lanes') AND lower(city) = lower('Brooklyn') AND state = 'NY';
UPDATE public.alleys SET lane_count = 14 WHERE lower(name) = lower('Lucky Strike Queens') AND lower(city) = lower('Woodside') AND state = 'NY';
UPDATE public.alleys SET lane_count = 40 WHERE lower(name) = lower('Westside Lanes & Fun Center') AND lower(city) = lower('Missoula') AND state = 'MT';
UPDATE public.alleys SET lane_count = 40 WHERE lower(name) = lower('Plaza Bowl') AND lower(city) = lower('Reno') AND state = 'NV';
UPDATE public.alleys SET lane_count = 32 WHERE lower(name) = lower('Summit Entertainment Center') AND lower(city) = lower('Windsor Locks') AND state = 'CT';
UPDATE public.alleys SET lane_count = 32 WHERE lower(name) = lower('Bronx Bowl') AND lower(city) = lower('Bronx') AND state = 'NY';
UPDATE public.alleys SET lane_count = 14 WHERE lower(name) = lower('Lucky Strike Manhattan') AND lower(city) = lower('New York') AND state = 'NY';
UPDATE public.alleys SET lane_count = 10 WHERE lower(name) = lower('Round1 Bowling & Arcade Valley Stream') AND lower(city) = lower('Valley Stream') AND state = 'NY';
UPDATE public.alleys SET lane_count = 32 WHERE lower(name) = lower('Spins Bowl Johnson City') AND lower(city) = lower('Johnson City') AND state = 'NY';
UPDATE public.alleys SET lane_count = 32 WHERE lower(name) = lower('Bowlarama') AND lower(city) = lower('Great Falls') AND state = 'MT';
UPDATE public.alleys SET lane_count = 16 WHERE lower(name) = lower('Indian Bowl Lanes') AND lower(city) = lower('Polson') AND state = 'MT';
UPDATE public.alleys SET lane_count = 32 WHERE lower(name) = lower('Silver Lanes') AND lower(city) = lower('East Granby') AND state = 'CT';
UPDATE public.alleys SET lane_count = 24 WHERE lower(name) = lower('Cougar Lanes') AND lower(city) = lower('Columbia Falls') AND state = 'MT';
UPDATE public.alleys SET lane_count = 40 WHERE lower(name) = lower('Lucky Strike Lanes') AND lower(city) = lower('Butte') AND state = 'MT';
UPDATE public.alleys SET lane_count = 32 WHERE lower(name) = lower('Sunset Lanes') AND lower(city) = lower('Havre') AND state = 'MT';
UPDATE public.alleys SET lane_count = 24 WHERE lower(name) = lower('Meadow Gold Lanes') AND lower(city) = lower('Missoula') AND state = 'MT';
UPDATE public.alleys SET lane_count = 16 WHERE lower(name) = lower('Rose Lanes') AND lower(city) = lower('Miles City') AND state = 'MT';
UPDATE public.alleys SET lane_count = 8 WHERE lower(name) = lower('Hi-Line Lanes') AND lower(city) = lower('Glasgow') AND state = 'MT';
UPDATE public.alleys SET lane_count = 40 WHERE lower(name) = lower('Emerald Lanes Family Center') AND lower(city) = lower('Helena') AND state = 'MT';
UPDATE public.alleys SET lane_count = 32 WHERE lower(name) = lower('Liberty Lanes') AND lower(city) = lower('Kalispell') AND state = 'MT';
UPDATE public.alleys SET lane_count = 10 WHERE lower(name) = lower('Round1 Bowling & Arcade Danbury Fair') AND lower(city) = lower('Danbury') AND state = 'CT';
UPDATE public.alleys SET lane_count = 10 WHERE lower(name) = lower('Round1 Bowling & Arcade Crossgates Mall') AND lower(city) = lower('Albany') AND state = 'NY';
UPDATE public.alleys SET lane_count = 16 WHERE lower(name) = lower('Concordia Lanes LLC') AND lower(city) = lower('Manchester') AND state = 'NH';
UPDATE public.alleys SET lane_count = 16 WHERE lower(name) = lower('Sunset Bowl') AND lower(city) = lower('Winsted') AND state = 'CT';
UPDATE public.alleys SET lane_count = 14 WHERE lower(name) = lower('Lucky Strike Long Island') AND lower(city) = lower('Farmingdale') AND state = 'NY';
UPDATE public.alleys SET lane_count = 40 WHERE lower(name) = lower('Whitey''s Bowling Lanes') AND lower(city) = lower('Hartford') AND state = 'CT';
UPDATE public.alleys SET lane_count = 50 WHERE lower(name) = lower('South Point Bowling Center') AND lower(city) = lower('Las Vegas') AND state = 'NV';
UPDATE public.alleys SET lane_count = 50 WHERE lower(name) = lower('Red Rock Lanes') AND lower(city) = lower('Las Vegas') AND state = 'NV';
UPDATE public.alleys SET lane_count = 50 WHERE lower(name) = lower('Sunset Station Strike Zone Bowling Center') AND lower(city) = lower('Henderson') AND state = 'NV';
UPDATE public.alleys SET lane_count = 40 WHERE lower(name) = lower('Brooklyn Bowl Las Vegas') AND lower(city) = lower('Las Vegas') AND state = 'NV';
UPDATE public.alleys SET lane_count = 50 WHERE lower(name) = lower('Sam''s Town Bowling Center') AND lower(city) = lower('Las Vegas') AND state = 'NV';
UPDATE public.alleys SET lane_count = 32 WHERE lower(name) = lower('Texas Station Bowling Center') AND lower(city) = lower('North Las Vegas') AND state = 'NV';
UPDATE public.alleys SET lane_count = 50 WHERE lower(name) = lower('Santa Fe Station Bowling Center') AND lower(city) = lower('Las Vegas') AND state = 'NV';
UPDATE public.alleys SET lane_count = 50 WHERE lower(name) = lower('The Gold Coast Bowling Center') AND lower(city) = lower('Las Vegas') AND state = 'NV';
UPDATE public.alleys SET lane_count = 36 WHERE lower(name) = lower('Bowlero North Brunswick') AND lower(city) = lower('North Brunswick Township') AND state = 'NJ';
UPDATE public.alleys SET lane_count = 32 WHERE lower(name) = lower('AMF Union Hills Lanes') AND lower(city) = lower('Glendale') AND state = 'AZ';
UPDATE public.alleys SET lane_count = 50 WHERE lower(name) = lower('Suncoast Bowling Center') AND lower(city) = lower('Las Vegas') AND state = 'NV';
UPDATE public.alleys SET lane_count = 24 WHERE lower(name) = lower('Hilton Bowling Center') AND lower(city) = lower('Las Vegas') AND state = 'NV';
UPDATE public.alleys SET lane_count = 50 WHERE lower(name) = lower('Wildfire Bowling') AND lower(city) = lower('Henderson') AND state = 'NV';
UPDATE public.alleys SET lane_count = 32 WHERE lower(name) = lower('Bowling at the Village') AND lower(city) = lower('Las Vegas') AND state = 'NV';
UPDATE public.alleys SET lane_count = 32 WHERE lower(name) = lower('Lucky Lanes') AND lower(city) = lower('Las Vegas') AND state = 'NV';
UPDATE public.alleys SET lane_count = 32 WHERE lower(name) = lower('Nellis Bowling Center') AND lower(city) = lower('Nellis AFB') AND state = 'NV';
UPDATE public.alleys SET lane_count = 8 WHERE lower(name) = lower('The Gutter') AND lower(city) = lower('Las Vegas') AND state = 'NV';
UPDATE public.alleys SET lane_count = 36 WHERE lower(name) = lower('Bowlero Sayville') AND lower(city) = lower('Sayville') AND state = 'NY';
UPDATE public.alleys SET lane_count = 36 WHERE lower(name) = lower('Bowlero Lake Grove') AND lower(city) = lower('Lake Grove') AND state = 'NY';
UPDATE public.alleys SET lane_count = 10 WHERE lower(name) = lower('Round1 Bowling & Arcade Fashion Outlets of Niagara Falls') AND lower(city) = lower('Niagara Falls') AND state = 'NY';
UPDATE public.alleys SET lane_count = 40 WHERE lower(name) = lower('AMF 34th Avenue Lanes') AND lower(city) = lower('Phoenix') AND state = 'AZ';
UPDATE public.alleys SET lane_count = 40 WHERE lower(name) = lower('Spins Bowl Tarrytown') AND lower(city) = lower('Tarrytown') AND state = 'NY';
UPDATE public.alleys SET lane_count = 24 WHERE lower(name) = lower('Hi-Tor Lanes') AND lower(city) = lower('West Haverstraw') AND state = 'NY';
UPDATE public.alleys SET lane_count = 32 WHERE lower(name) = lower('Webster Rec Bowling Center') AND lower(city) = lower('Webster') AND state = 'NY';
UPDATE public.alleys SET lane_count = 32 WHERE lower(name) = lower('Spins Bowl Poughkeepsie') AND lower(city) = lower('Poughkeepsie') AND state = 'NY';
UPDATE public.alleys SET lane_count = 32 WHERE lower(name) = lower('Spins Bowl New Paltz') AND lower(city) = lower('New Paltz') AND state = 'NY';
UPDATE public.alleys SET lane_count = 40 WHERE lower(name) = lower('Strikes ''n Spares Entertainment Center') AND lower(city) = lower('Mishawaka') AND state = 'IN';
UPDATE public.alleys SET lane_count = 36 WHERE lower(name) = lower('Bowlero Milford') AND lower(city) = lower('Milford') AND state = 'CT';
UPDATE public.alleys SET lane_count = 36 WHERE lower(name) = lower('Bowlero Staten Island') AND lower(city) = lower('Staten Island') AND state = 'NY';
UPDATE public.alleys SET lane_count = 36 WHERE lower(name) = lower('Bowlero Chelsea Piers') AND lower(city) = lower('New York') AND state = 'NY';
UPDATE public.alleys SET lane_count = 36 WHERE lower(name) = lower('Bowlero Commack') AND lower(city) = lower('East Northport') AND state = 'NY';
UPDATE public.alleys SET lane_count = 36 WHERE lower(name) = lower('Bowlero Farmingdale') AND lower(city) = lower('Farmingdale') AND state = 'NY';
UPDATE public.alleys SET lane_count = 24 WHERE lower(name) = lower('Bowling on Broadway') AND lower(city) = lower('Depew') AND state = 'NY';
UPDATE public.alleys SET lane_count = 40 WHERE lower(name) = lower('Pin Strikes - Columbus') AND lower(city) = lower('Columbus') AND state = 'GA';
UPDATE public.alleys SET lane_count = 36 WHERE lower(name) = lower('Bowlero Patchogue') AND lower(city) = lower('Patchogue') AND state = 'NY';
UPDATE public.alleys SET lane_count = 24 WHERE lower(name) = lower('Whitestone Lanes') AND lower(city) = lower('Flushing') AND state = 'NY';
UPDATE public.alleys SET lane_count = 36 WHERE lower(name) = lower('Bowlero Amsterdam') AND lower(city) = lower('New York') AND state = 'NY';
UPDATE public.alleys SET lane_count = 32 WHERE lower(name) = lower('Herrill Lanes Bowling Center') AND lower(city) = lower('New Hyde Park') AND state = 'NY';
UPDATE public.alleys SET lane_count = 24 WHERE lower(name) = lower('Jib Lanes') AND lower(city) = lower('Flushing') AND state = 'NY';
UPDATE public.alleys SET lane_count = 40 WHERE lower(name) = lower('Holler House') AND lower(city) = lower('Milwaukee') AND state = 'WI';
UPDATE public.alleys SET lane_count = 32 WHERE lower(name) = lower('AMF Lancaster Lanes') AND lower(city) = lower('Lancaster') AND state = 'NY';
UPDATE public.alleys SET lane_count = 32 WHERE lower(name) = lower('AMF Thruway Lanes') AND lower(city) = lower('Walden') AND state = 'NY';
UPDATE public.alleys SET lane_count = 32 WHERE lower(name) = lower('Flamingo Bowling') AND lower(city) = lower('Las Vegas') AND state = 'NV';
UPDATE public.alleys SET lane_count = 32 WHERE lower(name) = lower('Bowl Long Island') AND lower(city) = lower('Patchogue') AND state = 'NY';
UPDATE public.alleys SET lane_count = 32 WHERE lower(name) = lower('Spins Bowl Mount Kisco') AND lower(city) = lower('Mount Kisco') AND state = 'NY';
UPDATE public.alleys SET lane_count = 32 WHERE lower(name) = lower('Broadway Bowling Center') AND lower(city) = lower('Depew') AND state = 'NY';
UPDATE public.alleys SET lane_count = 8 WHERE lower(name) = lower('Bowling Green NYC') AND lower(city) = lower('New York') AND state = 'NY';
UPDATE public.alleys SET lane_count = 32 WHERE lower(name) = lower('AMF Sheridan Lanes') AND lower(city) = lower('Tonawanda') AND state = 'NY';
UPDATE public.alleys SET lane_count = 32 WHERE lower(name) = lower('Larkfield Lanes') AND lower(city) = lower('East Northport') AND state = 'NY';
UPDATE public.alleys SET lane_count = 32 WHERE lower(name) = lower('Coram Country Lanes') AND lower(city) = lower('Coram') AND state = 'NY';
UPDATE public.alleys SET lane_count = 32 WHERE lower(name) = lower('Maple Lanes RVC') AND lower(city) = lower('Rockville Centre') AND state = 'NY';
UPDATE public.alleys SET lane_count = 16 WHERE lower(name) = lower('Alton Lanes') AND lower(city) = lower('Galloway') AND state = 'NJ';
UPDATE public.alleys SET lane_count = 32 WHERE lower(name) = lower('Seaview Lanes') AND lower(city) = lower('Pacifica') AND state = 'CA';
UPDATE public.alleys SET lane_count = 32 WHERE lower(name) = lower('Pins at Valley Forge Casino Resort') AND lower(city) = lower('King of Prussia') AND state = 'PA';
UPDATE public.alleys SET lane_count = 50 WHERE lower(name) = lower('Splitsville') AND lower(city) = lower('Foxborough') AND state = 'MA';
UPDATE public.alleys SET lane_count = 40 WHERE lower(name) = lower('10 Pin Alley') AND lower(city) = lower('Hilliard') AND state = 'OH';
UPDATE public.alleys SET lane_count = 32 WHERE lower(name) = lower('Baxter''s') AND lower(city) = lower('West Babylon') AND state = 'NY';
UPDATE public.alleys SET lane_count = 32 WHERE lower(name) = lower('Rab''s Country Lanes') AND lower(city) = lower('Staten Island') AND state = 'NY';
UPDATE public.alleys SET lane_count = 32 WHERE lower(name) = lower('AMF East Meadow Lanes') AND lower(city) = lower('East Meadow') AND state = 'NY';
UPDATE public.alleys SET lane_count = 24 WHERE lower(name) = lower('Farmingdale Lanes') AND lower(city) = lower('Farmingdale') AND state = 'NY';
UPDATE public.alleys SET lane_count = 24 WHERE lower(name) = lower('Wm. S. Lott Jr. Lanes') AND lower(city) = lower('Syracuse') AND state = 'NY';
UPDATE public.alleys SET lane_count = 32 WHERE lower(name) = lower('Cortland Bowl') AND lower(city) = lower('Cortland') AND state = 'NY';
UPDATE public.alleys SET lane_count = 24 WHERE lower(name) = lower('Kingpin''s Alley Family Fun Center South Glens Falls, NY.') AND lower(city) = lower('South Glens Falls') AND state = 'NY';
UPDATE public.alleys SET lane_count = 40 WHERE lower(name) = lower('Lake Effect Bowling Center') AND lower(city) = lower('Watertown') AND state = 'NY';
UPDATE public.alleys SET lane_count = 24 WHERE lower(name) = lower('Little Kings & Queens Fun Place') AND lower(city) = lower('Cortlandt Manor') AND state = 'NY';
UPDATE public.alleys SET lane_count = 24 WHERE lower(name) = lower('Spins Bowl Carmel') AND lower(city) = lower('Carmel Hamlet') AND state = 'NY';
UPDATE public.alleys SET lane_count = 32 WHERE lower(name) = lower('Route 7 Bowling Center') AND lower(city) = lower('Hoosick Falls') AND state = 'NY';
UPDATE public.alleys SET lane_count = 32 WHERE lower(name) = lower('Pin Strikes') AND lower(city) = lower('Dawsonville') AND state = 'GA';
UPDATE public.alleys SET lane_count = 24 WHERE lower(name) = lower('All Star Recreation') AND lower(city) = lower('Chittenango') AND state = 'NY';
UPDATE public.alleys SET lane_count = 32 WHERE lower(name) = lower('Cortland Lanes') AND lower(city) = lower('Cortland') AND state = 'NY';
UPDATE public.alleys SET lane_count = 40 WHERE lower(name) = lower('Spins Bowl Port Jeff') AND lower(city) = lower('Port Jefferson Station') AND state = 'NY';
UPDATE public.alleys SET lane_count = 24 WHERE lower(name) = lower('AMF Indian Hills Lanes') AND lower(city) = lower('Clarksburg') AND state = 'WV';
UPDATE public.alleys SET lane_count = 32 WHERE lower(name) = lower('AMF Sheepshead Bay Lanes') AND lower(city) = lower('Brooklyn') AND state = 'NY';
UPDATE public.alleys SET lane_count = 32 WHERE lower(name) = lower('Lakeview Lanes') AND lower(city) = lower('Fulton') AND state = 'NY';
UPDATE public.alleys SET lane_count = 32 WHERE lower(name) = lower('AMF Plainview Lanes') AND lower(city) = lower('Plainview') AND state = 'NY';
UPDATE public.alleys SET lane_count = 40 WHERE lower(name) = lower('Brooklyn Bowl') AND lower(city) = lower('Brooklyn') AND state = 'NY';
UPDATE public.alleys SET lane_count = 8 WHERE lower(name) = lower('Sunset Lanes') AND lower(city) = lower('West Point') AND state = 'NE';
UPDATE public.alleys SET lane_count = 16 WHERE lower(name) = lower('Linden Lanes') AND lower(city) = lower('Wahoo') AND state = 'NE';
UPDATE public.alleys SET lane_count = 40 WHERE lower(name) = lower('Zorba''s') AND lower(city) = lower('Brooklyn') AND state = 'NY';
UPDATE public.alleys SET lane_count = 32 WHERE lower(name) = lower('Bowl 360 Brooklyn') AND lower(city) = lower('Brooklyn') AND state = 'NY';
UPDATE public.alleys SET lane_count = 24 WHERE lower(name) = lower('AMF Bay Shore Lanes') AND lower(city) = lower('Bay Shore') AND state = 'NY';
UPDATE public.alleys SET lane_count = 24 WHERE lower(name) = lower('Walden Lanes') AND lower(city) = lower('Walden') AND state = 'NY';
UPDATE public.alleys SET lane_count = 40 WHERE lower(name) = lower('King Louis Lanes') AND lower(city) = lower('Dallas') AND state = 'TX';
UPDATE public.alleys SET lane_count = 24 WHERE lower(name) = lower('Vogt Bowling Center') AND lower(city) = lower('New Rochelle') AND state = 'NY';
UPDATE public.alleys SET lane_count = 32 WHERE lower(name) = lower('AMF Carolier Lanes') AND lower(city) = lower('North Brunswick Township') AND state = 'NJ';
UPDATE public.alleys SET lane_count = 40 WHERE lower(name) = lower('Linden Lanes') AND lower(city) = lower('Linden') AND state = 'NJ';
UPDATE public.alleys SET lane_count = 32 WHERE lower(name) = lower('Playdrome Bowling Center') AND lower(city) = lower('Cherry Hill Township') AND state = 'NJ';
UPDATE public.alleys SET lane_count = 36 WHERE lower(name) = lower('Bowlero Lowell') AND lower(city) = lower('Lowell') AND state = 'MA';
UPDATE public.alleys SET lane_count = 24 WHERE lower(name) = lower('Clover Lanes') AND lower(city) = lower('Rochester') AND state = 'NY';
UPDATE public.alleys SET lane_count = 32 WHERE lower(name) = lower('Delaware Lanes Bowling Center') AND lower(city) = lower('Delran') AND state = 'NJ';
UPDATE public.alleys SET lane_count = 36 WHERE lower(name) = lower('Bowlero Kenilworth') AND lower(city) = lower('Kenilworth') AND state = 'NJ';
UPDATE public.alleys SET lane_count = 24 WHERE lower(name) = lower('Woodhaven Lanes') AND lower(city) = lower('Woodhaven') AND state = 'NY';
UPDATE public.alleys SET lane_count = 32 WHERE lower(name) = lower('Cape Square Entertainment') AND lower(city) = lower('Rio Grande') AND state = 'NJ';
UPDATE public.alleys SET lane_count = 36 WHERE lower(name) = lower('Bowlero Roxbury') AND lower(city) = lower('Succasunna') AND state = 'NJ';
UPDATE public.alleys SET lane_count = 36 WHERE lower(name) = lower('Bowlero Sicklerville') AND lower(city) = lower('Sicklerville') AND state = 'NJ';
UPDATE public.alleys SET lane_count = 32 WHERE lower(name) = lower('Howell Lanes') AND lower(city) = lower('Howell Township') AND state = 'NJ';
UPDATE public.alleys SET lane_count = 32 WHERE lower(name) = lower('Slocum Lanes Inc.') AND lower(city) = lower('Syracuse') AND state = 'NY';
UPDATE public.alleys SET lane_count = 24 WHERE lower(name) = lower('Classic Lanes') AND lower(city) = lower('Rochester') AND state = 'NY';
UPDATE public.alleys SET lane_count = 32 WHERE lower(name) = lower('South Amboy Lanes') AND lower(city) = lower('South Amboy') AND state = 'NJ';
UPDATE public.alleys SET lane_count = 14 WHERE lower(name) = lower('Lucky Strike Morristown') AND lower(city) = lower('Morristown') AND state = 'NJ';
UPDATE public.alleys SET lane_count = 26 WHERE lower(name) = lower('Oakwood Lanes') AND lower(city) = lower('Washington') AND state = 'NJ';
UPDATE public.alleys SET lane_count = 32 WHERE lower(name) = lower('Garwood Lanes') AND lower(city) = lower('Garwood') AND state = 'NJ';
UPDATE public.alleys SET lane_count = 32 WHERE lower(name) = lower('Brunswick Zone Carolier') AND lower(city) = lower('North Brunswick Township') AND state = 'NJ';
UPDATE public.alleys SET lane_count = 32 WHERE lower(name) = lower('Stelton Lanes') AND lower(city) = lower('Piscataway') AND state = 'NJ';
UPDATE public.alleys SET lane_count = 40 WHERE lower(name) = lower('Bowler City') AND lower(city) = lower('Hackensack') AND state = 'NJ';
UPDATE public.alleys SET lane_count = 32 WHERE lower(name) = lower('Hudson Lanes') AND lower(city) = lower('Jersey City') AND state = 'NJ';
UPDATE public.alleys SET lane_count = 8 WHERE lower(name) = lower('A1 Bowling Products') AND lower(city) = lower('Oakland') AND state = 'NJ';
UPDATE public.alleys SET lane_count = 10 WHERE lower(name) = lower('Round1 Bowling & Arcade') AND lower(city) = lower('Elizabeth') AND state = 'NJ';
UPDATE public.alleys SET lane_count = 10 WHERE lower(name) = lower('Round1 Bowling & Arcade') AND lower(city) = lower('Deptford') AND state = 'NJ';
UPDATE public.alleys SET lane_count = 16 WHERE lower(name) = lower('Alton Lanes') AND lower(city) = lower('Galloway') AND state = 'NJ';
UPDATE public.alleys SET lane_count = 32 WHERE lower(name) = lower('Brunswick Majestic Lanes') AND lower(city) = lower('Hopelawn') AND state = 'NJ';
UPDATE public.alleys SET lane_count = 32 WHERE lower(name) = lower('Brunswick Zone XL Carolier') AND lower(city) = lower('North Brunswick Township') AND state = 'NJ';
UPDATE public.alleys SET lane_count = 24 WHERE lower(name) = lower('Brad''s Triple Treat Bowling Center') AND lower(city) = lower('Vineland') AND state = 'NJ';
UPDATE public.alleys SET lane_count = 36 WHERE lower(name) = lower('Bowlero New Brunswick') AND lower(city) = lower('North Brunswick Township') AND state = 'NJ';
UPDATE public.alleys SET lane_count = 8 WHERE lower(name) = lower('Better Off Bowling - New York') AND lower(city) = lower('New York') AND state = 'NY';
UPDATE public.alleys SET lane_count = 8 WHERE lower(name) = lower('The New York Lawn Bowling Club') AND lower(city) = lower('New York') AND state = 'NY';
UPDATE public.alleys SET lane_count = 36 WHERE lower(name) = lower('Bowlero North Brunswick') AND lower(city) = lower('North Brunswick Township') AND state = 'NJ';
UPDATE public.alleys SET lane_count = 36 WHERE lower(name) = lower('Bowlero Sayville') AND lower(city) = lower('Sayville') AND state = 'NY';
UPDATE public.alleys SET lane_count = 36 WHERE lower(name) = lower('Bowlero Lake Grove') AND lower(city) = lower('Lake Grove') AND state = 'NY';
UPDATE public.alleys SET lane_count = 10 WHERE lower(name) = lower('Round1 Bowling & Arcade Fashion Outlets of Niagara Falls') AND lower(city) = lower('Niagara Falls') AND state = 'NY';